apiVersion: v1
kind: Service
metadata:
  name: llamacpp-server
  namespace: llamacpp
spec:
  type: NodePort
  selector:
    app: llamacpp
  ports:
    - name: http
      port: 8033
      targetPort: 8033
      nodePort: 30833
