apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-rollouts-demo
  namespace: argo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: fastapi-rollouts-demo
  template:
    metadata:
      labels:
        app: fastapi-rollouts-demo
    spec:
      containers:
        - name: fastapi-rollouts-demo
          image: 192.168.0.112:5000/fastapi-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
  strategy:
    canary:
      # Minimal canary strategy, just to show Rollouts in action
      steps:
        - setWeight: 50
        - pause: { duration: 30 }   # 30s pause at 50% traffic
        - setWeight: 100

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-rollouts-demo
  namespace: argo
spec:
  type: NodePort
  selector:
    app: fastapi-rollouts-demo
  ports:
    - name: http
      port: 8080          # service port (inside cluster)
      targetPort: 80      # FastAPI container port
      nodePort: 32211     # fixed NodePort on Ubuntu host
