apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tgi-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: tgi-hostpath
