apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ollama-hostpath
  hostPath:
    path: /mnt/ssd2/ollama/ollama
    type: DirectoryOrCreate
