apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - name: http
      port: 11434       # Cluster IP port
      targetPort: 11434 # Container port
      nodePort: 31500   # Host (Ubuntu) port
