apiVersion: v1
kind: Service
metadata:
  name: ollama-rollout-svc
  namespace: ollama
spec:
  type: NodePort
  selector:
    app: ollama
  ports:
    - name: http
      port: 11434        # internal cluster port
      targetPort: 11434  # container port
      nodePort: 31501    # NEW NodePort for Rollouts version
